name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@751ed07ce3ad102e310ee654155be6114ed7a95c
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@751ed07ce3ad102e310ee654155be6114ed7a95c
    if: always() && !cancelled()
    needs: build
